#!/usr/bin/env bash

set -o pipefail

SONATYPE_USER=$1
SONATYPE_PASSWORD=$2
PGP_SIGNING_KEY=$3
PGP_SIGNING_PASSWORD=$4

echo "Publishing Model Forge"
./gradlew -PMAVEN_UPLOAD_USER="$SONATYPE_USER" -PMAVEN_UPLOAD_PWD="$SONATYPE_PASSWORD" \
    -PPGP_SIGNING_KEY="$PGP_SIGNING_KEY" -PPGP_SIGNING_PASSWORD="$PGP_SIGNING_PASSWORD" build publish
