name: Release ✈️

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Version Bump
        uses: hopeman15/verselicious@2919a1ce90601bfd54fed5107338c28c6975dc64 # v0.3.0
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          major_label: 'major :1st_place_medal:'
          minor_label: 'minor :2nd_place_medal:'
          patch_label: 'patch :3rd_place_medal:'
