name: Labeling

on:
  pull_request:
    types: [ synchronize, opened, reopened, labeled, unlabeled ]

jobs:
  labeling:
    name: Adding Labels
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      pull-requests: write
    steps:
      - name: Labeling
        uses: hopeman15/auto-labeler@0.1.1
