name: Labeling

on:
  pull_request:
    types: [ synchronize, opened, reopened ]

jobs:
  labeling:
    name: Adding Labels
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}
      REPO: ${{ github.repository_owner }}/${{ github.event.repository.name }}
    steps:
      - name: Dependencies
        run: |
          gh pr edit $PR_NUMBER --add-label 'dependencies' -R $REPO
