name: Model Forge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  documentation:
    name: Generate Dokka Docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17','19' ]
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Generate Docs
        run: make docs

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17','19' ]
    name: Test with Java ${{ matrix.java }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Lint
        run: make lint
      - name: Test
        run: make test

  report:
    name: "Report"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: "Generate Coverage Report"
        run: make coverage
      - name: "Upload Coverage Report"
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: ./build/reports/kover/report.xml
          token: ${{ secrets.CODECOV_TOKEN }}
