name: Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
          cache: 'yarn'
          cache-dependency-path: 'website/yarn.lock'

      - name: Lint
        run: make lint-docs

      - name: Install Dependencies
        working-directory: website/
        run: yarn install

      - name: Build the Website
        working-directory: website/
        run: yarn build

      - name: Deploy Github Pages (only on main)
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          folder: website/build/
